baseurl:
markdown: redcarpet
pygments: true
lsi: false
permalink: /:categories/:title
excerpt_separator: "\n\n"
exclude:
  - Gruntfile.js
  - brix-core.sublime-project
  - package.json
  - readme.md
  - node_modules