excerpt_separator: "\n\n"
exclude:
  - Gruntfile.js
  - node_modules
  - package.json
  - README.md

title: THX
url: https://thx.github.io

permalink: /:categories/:title

gems:
  - jekyll-feed
  - jekyll-sitemap