baseurl:
highlighter: true
lsi: false
permalink: /:categories/:title
excerpt_separator: "\n\n"
exclude:
  - Gruntfile.js
  - brix-core.sublime-project
  - package.json
  - readme.md
  - node_modules

markdown: redcarpet
redcarpet:
  extensions:
    - with_toc_data
    - tables

title: THX
encoding: utf-8
